# The ID of the GitHub app associated to the deployment
github_app_id: 99999

# The private key of the GitHub app associated to the deployment
github_app_key: |-
  -----BEGIN RSA PRIVATE KEY-----
  <SECRET BASE64 GOES HERE>
  -----END RSA PRIVATE KEY-----

# The secret that GitHub will use to sign webhook events
webhook_secret: "very secret string"

# The DSN used to log traces to Sentry
sentry_dsn: "https://examplePublicKey@o0.ingest.sentry.io/0"

# The email address used for the Let's Encrypt ACME account
letsencrypt_email: "example@example.com"

# The API token for Bencher
bencher_api_token: "jwt_header.jwt_payload.jwt_verify_signature"

# The Bencher Project ID (optional)
bencher_project_id: "rustls"

# The Bencher Testbed ID (optional)
bencher_testbed_id: "benchmarking-host"
